/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FileGrid: typeof import('./components/FileGrid.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    FileList: typeof import('./components/FileList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RecursiveMenu: typeof import('./components/RecursiveMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
